export const NavbarMenu =[
    {
        id:1,
        title:'home',
        link:"/",
    },
    {
        id:2,
        title:'About',
        link:"#",
    },
    {
        id:3,
        title:'Program',
        link:"#",
    },
    {
        id:4,
        title:'Blogs',
        link:"#",
    },
]